### ISSUE TITLE
Clarification on a column of data.

### ISSUE THREAD

**Issue by maqorbani** [yueAUW/neural-daylighting#3]
Hey everyone!

I had a question about a column of the training data used by the algorithm to predict the luminance maps, as mentioned in the paper, they are the average luminance per each pixel, I wanted to make sure if they are the average luminance per pixel for all of the images in the training set.

It's the 7th column of processed_train_250_combine.npy: [..., 6].

![image](https://user-images.githubusercontent.com/47574645/91438882-52744c00-e881-11ea-9dbb-f5a8f4dcb90b.png)

**Comment by alexcolburn** [comment]
Hi,

Yes, the average should be for the training set only.   

For specifics of this codebase, it would be helpful to know the file name, and line number to track down the code.  Yue wrote the code a while ago, and I can't easily find the snippet from your description.

**Comment by maqorbani** [comment]
Yeah, that's exactly what I needed.

Another issue I had was the fact that the second input branch to your model (sunpatch images) consists of 600 nodes as in the PredictLumMaps.py, but is says 400 fully connected nodes on the paper

![image](https://user-images.githubusercontent.com/47574645/91469213-59628500-e8a8-11ea-9e86-c3807446a76c.png)

I sincerely appreciate your help.

**Comment by yueAUW** [comment]
Yes, the paper is right. Please note that the second input in the code actually refers to the first input in the paper. I did test different parameters (# of nodes in each layer) after publishing the paper. We will correct the code. Thanks for the feedbacks.
