### ISSUE TITLE
Importing .HDR image values as a tensor

### ISSUE THREAD

**Issue by maqorbani** [yueAUW/neural-daylighting#4]
Hey everyone! I hope you are all well.

May I ask you the best method for importing the pixel luminance values data from rpict to python?
I rendered *.hdr pictures using rpict and used pvalues to extract their pixel values in ASCII format, for the python import. but it takes a large amount of storage.

Thank you.

**Comment by maqorbani** [comment]
OpenCV library can easily read HDR images. (Using -1 as the flag on imread method) The older comment was before I figure this out.

**Comment by yueAUW** [comment]
Hi Mohammad，

Sorry for the late reply. Yes, OpenCV with -1 option can be used to read
HDR images. But please note that it might not be a reliable method in some
cases.  The most reliable method I found is still through a Radiance
function called Pvalue (
https://floyd.lbl.gov/radiance/man_html/pvalue.1.html). It will need one
extra step if we want to read HDRs into Python: 1)Pvalue convert HDR to
txt, and 2) read txt into Python. We did a comparison test between pixel
RGB/Luminance values output by OpenCV (-1 flag)，Pvalue method, and
Photosphere/HDRScope this Summer, and found in some cases OpenCV will give
very different results (1/3 or 1/2 of pixel luminance values ). If you want
to use OpenCV, you might want to do a quick check by comparing the
statistics of the input HDRs read by OpenCV versus Photosphere. If they
have similar statistics, you can proceed to finish the rest steps. Hope it
helps~

Yue

**Comment by maqorbani** [comment]
I sincerely appreciate your reply, Yue, and thank you for sharing the results of your experiment.
One issue with Pvalue is that it saves files in ASCII format therefore it takes large amounts of disk space. so a good practice might be to automate reading each HDR and saving its value, loading it into NumPy and saving the result as npy format, then removing the text file generated by the Pvalue right away.
